- name: Create container
  docker_image:
    name: "{{ image_name }}"
    path: "{{ playbook_dir }}/.."
    dockerfile: "{{ dockerfile }}"

- name: Start container
  docker_container:
    image: "{{ image_name }}"
    name: "{{ container_name }}"
    detach: yes
    # Workaround for: https://github.com/ansible/ansible-modules-core/issues/1885
    network_mode: bridge
    tty: yes
    command: sleep infinity
    state: started

# dynamically update inventory to make it available down the playbook
- name: Register container
  add_host: 
    name: "{{ host_name }}"
